### ISSUE TITLE
Error on member details page

### ISSUE THREAD

**Issue by michal-michalak** [mxenabled/atrium-demo#1]
Why do I get an error when visiting member details page? Is this app works on dev?

![member-details](https://user-images.githubusercontent.com/10532319/80399431-74e95f00-88b9-11ea-8288-619f8cf8eaf8.png)

```
Started GET "/members/1" for ::1 at 2020-04-27 19:00:04 +0200
Processing by MembersController#show as HTML
  Parameters: {"id"=>"1"}
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Member Load (0.6ms)  SELECT "members".* FROM "members" WHERE "members"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/members_controller.rb:41:in `show'
ETHON: performed EASY effective_url=https://vestibule.mx.com/users/USR-ab0c5e6b-ca1d-46c0-ae42-de0f1706f4c9/members/MBR-af50cf81-422e-4764-9a7b-2744fbcdfce1/status response_code=200 return_code=ok total_time=0.222344
  ConnectionStatus Load (0.4ms)  SELECT "connection_statuses".* FROM "connection_statuses" WHERE "connection_statuses"."name" = $1 LIMIT $2  [["name", "DENIED"], ["LIMIT", 1]]
  ↳ app/controllers/members_controller.rb:43:in `show'
ETHON: performed EASY effective_url=https://vestibule.mx.com/institutions/mxbank response_code=200 return_code=ok total_time=0.24917
ETHON: performed EASY effective_url=https://vestibule.mx.com/users/USR-ab0c5e6b-ca1d-46c0-ae42-de0f1706f4c9/members/MBR-af50cf81-422e-4764-9a7b-2744fbcdfce1/accounts response_code=200 return_code=ok total_time=0.229522
  Rendering members/show.html.erb within layouts/application
  Rendered members/show.html.erb within layouts/application (Duration: 2.4ms | Allocations: 1267)
Completed 500 Internal Server Error in 736ms (ActiveRecord: 1.7ms | Allocations: 6564)


  
ActionView::Template::Error (undefined method `name' for nil:NilClass):
    3:     <div class="box member-box is-dark-gray top-margin-small">
    4:       <div class='card is-dark-gray'>
    5:         <%= @member_guid %>
    6:         <% unless @connection_status.name == "CONNECTED" %>
    7:           <p class="title is-4 has-text-white"><%= @connection_status.name %></p>
    8:           <p class="subtitle is-6 has-text-white"><%= @connection_status.message %></p>
    9:           <%= link_to "Resolve Issues", edit_registrations_path(id: @member.id), class: "button is-fullwidth member-control-button resolve-issue" %>
  
app/views/members/show.html.erb:6
```

**Comment by jgerlach** [comment]
I just updated the readme to explain more in depth how to get the app up and running. Let me know if it helps solve your issue.
